
//-- AUTOMATICALLY GENERATED BY CDK -- DO NOT EDIT --

#include <cdk/ast/all.h>


#ifdef __NODE_DECLARATIONS_ONLY__

namespace l22 {

class evaluation_node;
class if_else_node;
class if_node;
class print_node;
class program_node;
class read_node;
class while_node;


} // namespace l22

#else /* !defined(__NODE_DECLARATIONS_ONLY__) */

#ifndef __AUTOMATIC_l22_NODE_ALL_NODES_H__
#define __AUTOMATIC_l22_NODE_ALL_NODES_H__

#include "ast/evaluation_node.h"
#include "ast/if_else_node.h"
#include "ast/if_node.h"
#include "ast/print_node.h"
#include "ast/program_node.h"
#include "ast/read_node.h"
#include "ast/while_node.h"


#endif /* !defined(__AUTOMATIC_l22_NODE_ALL_NODES_H__) */
#endif /* !defined(__NODE_DECLARATIONS_ONLY__) */

