
//-- AUTOMATICALLY GENERATED BY CDK -- DO NOT EDIT --
#include <cdk/ast/visitor_decls.h>

#ifdef __IN_VISITOR_HEADER__
#ifdef __PURE_VIRTUAL_DECLARATIONS_ONLY__
  virtual void do_evaluation_node(l22::evaluation_node *const node, int lvl) = 0;
  virtual void do_if_else_node(l22::if_else_node *const node, int lvl) = 0;
  virtual void do_if_node(l22::if_node *const node, int lvl) = 0;
  virtual void do_print_node(l22::print_node *const node, int lvl) = 0;
  virtual void do_program_node(l22::program_node *const node, int lvl) = 0;
  virtual void do_read_node(l22::read_node *const node, int lvl) = 0;
  virtual void do_while_node(l22::while_node *const node, int lvl) = 0;

#else
  void do_evaluation_node(l22::evaluation_node *const node, int lvl);
  void do_if_else_node(l22::if_else_node *const node, int lvl);
  void do_if_node(l22::if_node *const node, int lvl);
  void do_print_node(l22::print_node *const node, int lvl);
  void do_program_node(l22::program_node *const node, int lvl);
  void do_read_node(l22::read_node *const node, int lvl);
  void do_while_node(l22::while_node *const node, int lvl);

#endif /* !defined(__PURE_VIRTUAL_DECLARATIONS_ONLY__) */
#endif /* __IN_VISITOR_HEADER__ */

